# PART 1:-  2 layer network(input/output)


In [2]:
import numpy as np
x = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0,0,1,1]]).T
x.shape

(4, 3)

 np.random.seed(1)

In [3]:
def none_linear(x, deriv=False):
    if deriv==True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [4]:
weg = 2*np.random.random((3,1))-1
weg

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [8]:
for i in range(10000):
    l0 = x
    l1 = none_linear(np.dot(l0,weg))
    
    l1_error = y - l1
    
    l1_delta = l1_error * none_linear(l1,True)
    
    weg += np.dot(l0.T, l1_delta)

In [9]:
print("Training data.........")
print(l1)

Training data.........
[[ 0.00966449]
 [ 0.00786506]
 [ 0.99358898]
 [ 0.99211957]]


# Part 2:- 3 layer network(input, hidden,output)

In [3]:
import numpy as np
X = np.array([[0,0,1],
[0,1,1],
[1,0,1],
[1,1,1]])

 
y = np.array([[0],
[1],
[1],
[0]])
 
np.random.seed(1)

In [4]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [5]:
weg0 = 2*np.random.random((3,4)) - 1
weg1 = 2*np.random.random((4,1)) - 1
weg0,weg1

(array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
        [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
        [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]]),
 array([[-0.5910955 ],
        [ 0.75623487],
        [-0.94522481],
        [ 0.34093502]]))

In [8]:
for j in range(60000):
    l0 = X
    l1 = nonlin(np.dot(l0,weg0))
    l2 = nonlin(np.dot(l1,weg1))
    l2_error = y - l2
    l2_delta = l2_error*nonlin(l2,deriv=True)
    l1_error = np.dot(l2_delta,weg1.T)
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    weg1 += l1.T.dot(l2_delta)
    weg0 += l0.T.dot(l1_delta)
    

In [9]:
print("Training data......")
print(l2)

Training data......
[[ 0.00260572]
 [ 0.99672209]
 [ 0.99701711]
 [ 0.00386759]]
